Repository patorseing/longfung-linehack-2023, pull requests merged in 2023-02, with the labels that each got.

#11 Fix/GitHub action
  .github/workflows/firebase-hosting-pull-request-be.yml
  .github/workflows/firebase-hosting-pull-request-ui.yml
  .gitignore
Labels: UI

#7 chore: test deploy env
  .github/workflows/firebase-hosting-pull-request-be.yml
  .github/workflows/firebase-hosting-pull-request-ui.yml
  frontend/features/registration/pages/BandRegister/index.tsx
  frontend/features/registration/pages/SelectTypePage.tsx
  frontend/lib/firebase/config.ts
  frontend/lib/hooks/axios.ts
  frontend/lib/hooks/getAppCheckToken.ts
  frontend/lib/theme/index.tsx
  frontend/package-lock.json
  frontend/package.json
  frontend/pages/_app.tsx
  frontend/pages/_document.tsx
Labels: UI

#8 feat: band registration api
  functions/package-lock.json
  functions/package.json
  functions/src/api/controllers/bands/bandController.ts
  functions/src/api/controllers/bands/types.ts
  functions/src/api/index.ts
  functions/src/api/routes/bandRoutes.ts
  functions/src/api/routes/healthcheck.ts
  functions/src/api/types.ts
  functions/src/api/utils/fileUploader.ts
  functions/src/api/utils/payload.ts
  functions/src/api/validators/bandValidators.ts
  functions/src/dialogflow/func/welcome.ts
  functions/src/firebase/index.ts
  functions/src/index.ts
  functions/src/line/beacon/enter.ts
  functions/src/line/beacon/index.ts
  storage.rules
Labels: BE

#13 feat: token authorization middle ware
  functions/src/api/controllers/bands/bandController.ts
  functions/src/api/dto/band.ts
  functions/src/api/middlewares/bandMiddleware.ts
  functions/src/api/middlewares/tokenVerification.ts
  functions/src/api/routes/bandRoutes.ts
  functions/src/firebase/index.ts
  functions/src/index.ts
Labels: BE

#19 BE: Feat/beacon welcome to festival
  .github/workflows/firebase-hosting-pull-request-be.yml
  .github/workflows/firebase-hosting-pull-request-ui.yml
  README.md
  functions/src/api/controllers/events/types.ts
  functions/src/index.ts
  functions/src/line/beacon/enter.ts
  functions/src/line/beacon/index.ts
  functions/src/line/index.ts
  functions/src/line/templete.ts
  functions/src/line/util.ts
Labels: review

#22 BE: add interested person to event
  functions/src/dialogflow/func/fallback.ts
  functions/src/dialogflow/func/index.ts
  functions/src/dialogflow/func/inputNumber.ts
  functions/src/dialogflow/func/interestEvent.ts
  functions/src/dialogflow/func/welcome.ts
  functions/src/dialogflow/index.ts
  functions/src/line/templete.ts
  functions/src/types/dialogflow-fulfillment.d.ts
Labels: review

#24 BE: cronjob remind event
  functions/package-lock.json
  functions/package.json
  functions/src/dialogflow/func/interestEvent.ts
  functions/src/dialogflow/index.ts
  functions/src/index.ts
  functions/src/line/beacon/enter.ts
  functions/src/line/index.ts
  functions/src/line/templete.ts
  functions/src/line/util.ts
  functions/src/types/dialogflow-fulfillment.d.ts
Labels: review

#29 feat: changed event path
  functions/src/line/beacon/enter.ts
  functions/src/line/index.ts
  functions/src/line/templete.ts
Labels: BE

#16 BE: update band api
  functions/package-lock.json
  functions/package.json
  functions/src/api/constants.ts
  functions/src/api/controllers/bands/bandController.ts
  functions/src/api/controllers/events/types.ts
  functions/src/api/dto/band.ts
  functions/src/api/dto/event.ts
  functions/src/api/middlewares/bandMiddleware.ts
  functions/src/api/routes/bandRoutes.ts
  functions/src/api/validators/bandValidators.ts
  functions/src/dialogflow/func/moreEventInfo.ts
  functions/src/line/beacon/enter.ts
  functions/src/line/index.ts
  functions/src/line/templete.ts
  functions/src/types/global.d.ts
Labels: BE

#32 BE: change create band validation rules
  functions/src/api/validators/bandValidators.ts
Labels: BE
